spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/imagelite
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB